#!/usr/bin/env sh
#
# ~/.xinitrc
#

ERRFILE="$XDG_CACHE_HOME"/X11/xsession-errors

[ "$(which fcitx 2 > /dev/null)" ] && fcitx -d & # input method
[ "$(which blueman-tray 2 > /dev/null)" ] && blueman-applet & # bluetooth
[ "$(which nm-applet 2 > /dev/null)" ] && nm-applet & # network
[ "$(which volumeicon 2 > /dev/null)" ] && volumeicon & # volum control
# [ "$(which pasystray 2 > /dev/null)" ] && pasystray & # volum control
[ "$(which polkit-dumb-agent 2 > /dev/null)" ] && polkit-dumb-agent &

# Cursor speed
xset r rate 300 50

# Xresource
[ -f ~/.config/X11/Xresources ] && xrdb -load ~/.config/X11/Xresources

# Key Mapping
[ -f ~/.config/X11/Xmodmap ] && xmodmap ~/.config/X11/Xmodmap

exec qtile start

