#!/usr/bin/env sh
export DISPLAY=${DISPLAY:-:0}
POWERSUPPLY="/sys/class/power_supply/AC/online"
TOO_LOW=12
NOT_CHARGING="0"

ICON="$HOME/.config/sway/icons/battery_icons_vert/battery-caution.png"

BATTERY_LEVEL=$(acpi -b | grep -P -o '[0-9]+(?=%)')
STATUS=$(cat "$POWERSUPPLY")

if [ "$BATTERY_LEVEL" -le "$TOO_LOW" ] && [ "$STATUS" = "$NOT_CHARGING" ]; then
    notify-send -i "$ICON" -t 30000 "Battery low" "Battery level is ${BATTERY_LEVEL}%!"
    if command -v brightnessctl >/dev/null 2>&1; then
        brightnessctl set 20%
    fi
fi

exit 0
