#!/usr/bin/env sh

session=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' \
    2>/dev/null | grep work | tail -n 1 | cut -d '|' -f1)
if [ "$session" = "" ]
then
    tmux new-session -s work -n paper -c "$HOME/work/cosmicShear/notebooks/paper" -d
    tmux split-window -t work.1 -v -p 26 -c "$HOME/work/cosmicShear/notebooks/paper" -d
    tmux neww -t work -n html -c "$HOME/work/cosmicShear/notebooks/html" -d
    $FILEMANAGER ~/Documents/Research/Papers/Galaxy/cosmicShear/
    xterm -T "work" -e "tmux attach -t work"
else
    ss2=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' \
        2>/dev/null | grep -v 'not attached' | grep work | tail -n 1 | cut -d '|' -f1)
    if [ "$ss2" = "" ]
    then
        xterm -T "work" -e "tmux attach -t work"
    fi
fi

rsync -zav --update --no-links $gw_ipmu:/work/xiangchong.li/work/cosmicShear "$HOME/work/"
