#!/usr/bin/env sh

tmux new-session -s publication -c ~/Tmp/Writing/cosmicShear_HSCY3 -d
tmux split-window -v -p 33 -c ~/Tmp/Writing/cosmicShear_HSCY3
$FILEMANAGER ~/Documents/Research/Papers/Galaxy/cosmicShear/
xterm -T "publication" -e "tmux attach -t publication"
