#!/usr/bin/env sh

session=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' \
    2>/dev/null | grep publication | tail -n 1 | cut -d '|' -f1)
if [ "$session" = "" ]
then
    tmux new-session -s publication -c ~/Tmp/Writing/cosmicShear_HSCY3 -d
    tmux split-window -v -p 33 -c ~/Tmp/Writing/cosmicShear_HSCY3
    $FILEMANAGER ~/Documents/Research/Papers/Galaxy/cosmicShear/
    xterm -T "publication" -e "tmux attach -t publication"
else
    xterm -T "$session" -e "tmux attach -t "$session""
fi
