#!/usr/bin/env sh

[ $atIPMU -eq 1 ] && backup

command -v rofi >/dev/null 2>&1 || exit
chosen=$(printf "Lock Screen\nLogout\nShut Down\nReboot" | rofi -dmenu -i -p "Choose Option" -lines 4)
[ "$chosen" != "" ] || exit

case "$chosen" in
	"Lock Screen") dm-tool lock;;
	"Logout") sudo service lightdm restart;;
	"Shut Down") shutdown now;;
	"Reboot") reboot;;
	*) exit;;
esac
