#!/usr/bin/env sh

[ $atIPMU -eq 1 ] && backup

[ "$(which dmenu 2>/dev/null)" ] || exit
chosen=$(printf "Lock Screen\nLogout\nShut Down\nReboot" | dmenu -g 1 -i -l 4 -fn Arial -p "Choose Option")
[ "$chosen" != "" ] || exit

case "$chosen" in
	"Lock Screen") dm-tool lock;;
	"Logout") sudo service lightdm restart;;
	"Shut Down") shutdown now;;
	"Reboot") reboot;;
	*) exit;;
esac
