#!/usr/bin/env sh
#LD_LID
export LD_LIBRARY_PATH="$homeSys/lib":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$homeSys/lib64":$LD_LIBRARY_PATH

[ "$(which tmux)" ] || exit
# Already in tmux
[ $TMUX ] && exit

# Get the first idel session name
session=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' \
    2>/dev/null | grep -v publication | grep 'not attached$' | tail -n 1 | cut -d '|' -f1)

if [ "$session" = "" ]
then
    nss=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' \
        2>/dev/null | sort -n | tail -n 1 | cut -d '|' -f1)
    let nss=nss+1
    xterm -T "Term$nss" -e "tmux"
else
    xterm -T "Term$session" -e "tmux attach -t "$session""
fi
