#!/usr/bin/env sh

# Which bookmark to choose
bm=$(ls $HOME/.local/xshare/bookmarks | dmenu -i -p 'choose the bookmark' -l 20 -fn Arial)
[ "$bm" != "" ] || exit

# Which concept to choose
chosen=$(grep -v "#" $HOME/.local/xshare/bookmarks/$bm | awk '{print $1}'| dmenu -i -p 'choose the concept' -l 20 -fn Arial)
[ "$chosen" != "" ] || exit

info=$(grep "$chosen" $HOME/.local/xshare/bookmarks/$bm)
pdf=$(echo "$info" | awk '{print $2}')
page=$(echo "$info" | awk '{print $3}')

[ "$pdf" != "" ] || exit
[ "$page" != "" ] || exit

filename=$(find $docDir/Research/Papers -name  "$pdf")

cmd="zathura -P $page $filename"
eval "$cmd"
