#!/usr/bin/env sh
# choose the server to login

# Make sure we have dmemu
[ "$(which dmenu 2>/dev/null)" ] || exit

# Which server to choose
chosen=$(grep -v "#" $HOME/.local/xshare/server.info | awk '{print $1}'| dmenu -g 1 -i -p 'choose the ssh server' -l 20 -fn Arial)
[ "$chosen" != "" ] || exit
c=$(grep "$chosen" $HOME/.local/xshare/server.info | awk '{print $2}')

# Login
xterm -T "$chosen" -e "ssh "$c""
