#!/usr/bin/env zsh
# choose the server to login

# Initialization
[ "$(ssh-add -l 2>/dev/null)" ] || ssh-add ~/.ssh/id_rsa

# Which server to choose
chosen=$(grep -v "#" $homeSys/xshare/server.info | awk '{print $1}'| dmenu -g 1 -i -p 'choose the ssh server' -l 20 -fn Arial)
[ "$chosen" != "" ] || exit

info=$(grep "$chosen" $homeSys/xshare/server.info)
s=$(echo "$info" | awk '{print $2}')
p=$(echo "$info" | awk '{print $3}')

[ "$p" != "" ] || exit

# Connet to remote Jupyter server
# input is the $(which jupyter) on server

port1="$p"
client=$(ssh "$s" cat \$HOME/.cache/jupyterlab.info | awk '{print $1}')
port3=$(ssh "$s" cat \$HOME/.cache/jupyterlab.info | awk '{print $2}')
# kill existing connections
pids=$(lsof -i :"$port1" | awk '/IPv4/ && /LISTEN/ {print $2}')
if [ pids ]; then
    kill $pids
fi

rm -rf ~/.cache

cmd="ssh -f -N -L "$port1":"$client":$port3 $s"
echo "$cmd"
eval "$cmd"
url="http://localhost:$port1"
echo "URL that will open in your browser:"
echo "$url"

brave "$url"
