#!/usr/bin/env sh
# choose the server to login

# Make sure we have rofi
command -v rofi >/dev/null 2>&1 || exit

# Which server to choose
chosen=$(grep -v "#" $HOME/.local/xshare/server.info | awk '{print $1}'| rofi -dmenu -i -p 'choose the ssh server' -lines 20)
[ "$chosen" != "" ] || exit
c=$(grep "$chosen" $HOME/.local/xshare/server.info | awk '{print $2}')

# Login
xterm -T "$chosen" -e "ssh "$c""
