#!/usr/bin/env sh

rsync -zav --force --update --delete-before /home/xiangchong/Documents/homepage/* $member_ipmu:/home/xiangchong.li/public_html/
rsync -zav --force --update --delete-after /home/xiangchong/Documents/homepage/tmp $member_ipmu:/home/xiangchong.li/public_html/

