#!/usr/bin/env sh

#rsync -zav --force --update --delete-after /home/xiangchong/Documents/homepage/* $member_ipmu:/home/xiangchong.li/public_html/
rsync -zav --force --update --delete-after /home/xiangchong/Documents/homepage/Life $gfarm_ipmu:/home/xiangchong.li/public_html/
rsync -zav --force --update --delete-after /home/xiangchong/Documents/homepage/me $gfarm_ipmu:/home/xiangchong.li/public_html/
rsync -zav --force --update --delete-after /home/xiangchong/Documents/homepage/Research $gfarm_ipmu:/home/xiangchong.li/public_html/
rsync -zav --force --update --delete-after /home/xiangchong/Documents/homepage/sys $gfarm_ipmu:/home/xiangchong.li/public_html/
rsync -zav --force --update --delete-after /home/xiangchong/Documents/homepage/tmp $gfarm_ipmu:/home/xiangchong.li/public_html/

