#!/usr/bin/env sh
# choose the server to login

# Make sure we have rofi
command -v rofi >/dev/null 2>&1 || exit

# Chose option
chosen=$(printf "Current Window\nRectangle Region" | rofi -dmenu -i -p 'snapshot on?' -lines 20)
[ "$chosen" != "" ] || exit

fname='%Y-%m-%d-%H-%M-%S.png'
case "$chosen" in
	"Current Window")
        scrot -d 1 -q 60 -u -z "$fname" -e 'xclip -selection clipboard -t image/png -i $f && mv $f ~/Documents/Snapshots/'
        ;;
	"Rectangle Region")
        scrot -d 1 -q 60 -l opacity=10 -s -f -z "$fname" -e 'xclip -selection clipboard -t image/png -i $f && mv $f ~/Documents/Snapshots/'
        ;;
	*)
        exit
        ;;
esac
