#!/usr/bin/env sh

if  [ $(xinput list-props "SynPS/2 Synaptics TouchPad" | grep 'Device Enabled'| gawk -F ':' '{ print $2 }') -eq 0 ]
then
    xinput enable "SynPS/2 Synaptics TouchPad"
else
    xinput disable "SynPS/2 Synaptics TouchPad"
fi
