#!/usr/bin/env zsh

convert $homeSys/xshare/wallpapers/Debian_Only.jpg \( <( curl wttr.in/"$currentcity"_ntqp2.png ) -resize 800x \) -geometry +20+300 -composite $HOME/Tmp/wallpaper.jpg

updateCalendar.py
convert -size 800x400 xc:#002b36 -pointsize 25 -fill white -annotate +20+25 "@Tmp/calendar.txt" $HOME/Tmp/calendar.jpg
convert $HOME/Tmp/wallpaper.jpg $HOME/Tmp/calendar.jpg -geometry +20+1200 -composite $HOME/Tmp/wallpaper.jpg
