#!/usr/bin/env sh
# choose the server to login

# Make sure we have rofi
command -v rofi >/dev/null 2>&1 || exit
# Make sure we have expect
[ "$(which expect)" ] || exit

# # A background server for communication
# [ "$(tmux ls 2>/dev/null | grep background )" ] || tmux new-session -d -s background

# Which server to choose
server=$(grep -v "#" $HOME/.local/xshare/vpn.info | awk '{print $1}' | rofi -dmenu -i -p 'choose the vpn server' -lines 20)
[ "$server" != "" ] || exit

chosen=$(grep "$server" $HOME/.local/xshare/vpn.info)
server=$(echo "$chosen" | awk '{print $1}')
usrname=$(echo "$chosen" | awk '{print $2}')
passwd=$(echo "$chosen" | awk '{print $3}')

# Login
if [ "$server" == "IPMU" ]
then
expect -f - <<EOD
    set timeout 7
    spawn /opt/cisco/anyconnect/bin/vpn connect vpngw.ipmu.jp
    expect "Group*" {send -- "\r"}
    expect "Username*" {send -- "$usrname\r"}
    expect "Password*" {send -- "$passwd\r"}
    expect "accept*" {send -- "y\r"}
    expect "Connected"
EOD
elif [ "$server" == "PAU" ]
then
    startct -m console remote.princeton.edu
fi
