#!/usr/bin/env sh

rsync -zav --update --no-links $idark_ipmu:/lustre/work/xiangchong.li/work/FPFS_detect/notebooks "$HOME/work/FPFS_detect/"
cp "$HOME"/work/FPFS_detect/notebooks/html/* "$HOME"/Documents/Research/Notes/TODO/2022/shear_estimate/

wname="Term-SM"
session=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' \
    2>/dev/null | grep "$wname" | tail -n 1 | cut -d '|' -f1)
if [ "$session" = "" ]
then
    tmux new-session -s "$wname" -n paper -c "$HOME/work/FPFS_detect/notebooks/paper" -d
    tmux split-window -t "$wname".1 -v -p 26 -c "$HOME/work/FPFS_detect/notebooks/paper" -d
    tmux neww -t "$wname" -n html -c "$HOME/work/FPFS_detect/notebooks/html" -d
    xterm -T "$wname" -e "tmux attach -t $wname"
else
    ss2=$(tmux ls -F '#{session_name}|#{?session_attached,attached,not attached}' \
        2>/dev/null | grep -v 'not attached' | grep "$wname" | tail -n 1 | cut -d '|' -f1)
    if [ "$ss2" = "" ]
    then
        xterm -T "$wname" -e "tmux attach -t $wname"
    fi
fi

